# Repository variablesのREPOSITORY_OWNERにユーザー名を登録しておく
name: Approve Owners Pull Request
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
jobs:
  approve:
    if: |
      github.event.pull_request.user.login == vars.REPOSITORY_OWNER
      && ! github.event.pull_request.draft
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: gh pr review ${{ github.event.number }} --approve
